# Generated by Django 6.0.2 on 2026-03-16 06:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('certification', '0001_initial'),
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseCertificationMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('primary_mapping', models.BooleanField(default=False)),
                ('certification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='certification.certification')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.course')),
            ],
            options={
                'verbose_name': 'course certification mapping',
                'verbose_name_plural': 'course certification mappings',
                'ordering': ['id'],
                'abstract': False,
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('course', 'certification'), name='unique_active_course_certification_mapping'), models.UniqueConstraint(condition=models.Q(('is_active', True), ('primary_mapping', True)), fields=('course',), name='unique_primary_certification_per_course')],
            },
        ),
    ]
